name: Build
on:
  workflow_call:

jobs:
  build:
    name: Build migrator
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 11
          cache: sbt
      - uses: sbt/setup-sbt@v1
      - name: Build migrator
        run: make build
      - name: Upload assembly JAR
        uses: actions/upload-artifact@v4
        with:
          name: migrator-jar
          path: migrator/target/scala-2.13/scylla-migrator-assembly.jar
          retention-days: 1
